#
# Grakn Labs
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run: bash ./tool/bazelinstall/linux.sh
      - run: bash ./tool/bazelinstall/rbe.sh
  
  run-bazel:
    parameters:
      command:
          type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run-bazel:
          command: bazel build //...

workflows:
  dependencies:
    jobs:
      - build
